# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Geunny's Blog
subtitle:         컴퓨터는 거짓말을 하지 않는다.
description:      알게된 것에 대한 생각정리
keywords:         demo theme example github jekyll features
language:         "ko" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:          "/geunny-blog" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:        /blog/:categories/:title
cover:            /assets/mountain-cover.jpg
disqus_shortname: "jekylldecent"

# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor, "developer-tools"]
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  startings: [head, body]
